DATA_DIR = ./data
DEPO_DIR = ./depo
PRED_DIR = ./predictions

clean:
	@rm -f $(DATA_DIR)/*.csv 
	@rm -f $(DEPO_DIR)/*.npy
	@rm -f $(PRED_DIR)/*.csv 
	@echo "\033[91mDeleted all CSV files in the data folder.\033[0m"
	@echo "\033[91mDeleted all NPY files in the depo folder.\033[0m"

